[package]
name = "uniplate"
version = "0.1.0"
edition = "2021"
description="Boilerplate-free generic operations on data, Haskell style."
license = "MPL-2.0"

[lib]

[dependencies]
thiserror = "1.0.57"

[lints]
workspace = true
