[package]
name = "uniplate"
version = "0.1.0"
edition = "2021"
description="Boilerplate-free generic operations on data, Haskell style."
license = "MPL-2.0"

[lib]

[dependencies]
im = {version = "15.1.0", features = ["proptest"]}
proptest = "1.4.0"
proptest-derive = "0.4.0"
thiserror = "1.0.61"

[lints]
workspace = true

[features]
unstable = []
