[package]
name = "chuffed_rs"
version = "0.1.0"
authors = ["Kieran Fowlds <kf77@st-andrews.ac.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0.96", features = ["parallel"] }
bindgen = "0.69.4"
