[package]
name = "conjure_rule_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"
syn = { version = "2.0.103", features = ["full"] }
proc-macro2 = "1.0.95"
linkme = "0.3.33"

[lints]
workspace = true
