[package]
name = "uniplate_derive"
version = "0.1.0"
edition = "2021"
description="Boilerplate-free generic operations on data, Haskell style."
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
syn = "2.0.52"
quote = "1.0.35"

[lints]
workspace = true
