[package]
name = "conjure_rules"
version = "0.1.0"
edition = "2021"

[dependencies]
conjure_rules_proc_macro = { path = "../conjure_rules_proc_macro" }
conjure_core = { path = "../conjure_core" }
linkme = "0.3.22"

[lints]
workspace = true
