[package]
name = "conjure-cp-core"
version = "0.0.1"
edition = "2024"

[features]
extra-rule-checks = []

[dependencies]
conjure-cp-rule-macros = { path = "../conjure-cp-rule-macros" }
conjure-cp-enum-compatibility-macro = { path = "../conjure-cp-enum-compatibility-macro" }
minion-sys = { path = "../minion-sys" }
tree-morph = {path = "../tree-morph"}

uniplate = {workspace = true}
project-root = {workspace = true}
linkme = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
serde_with = {workspace = true}
strum = {workspace = true}
strum_macros = {workspace = true}
thiserror = {workspace = true}
log = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
anyhow = {workspace = true}
regex = {workspace = true}
walkdir = {workspace = true}
derivative = {workspace = true}
schemars = {workspace = true}
clap = {workspace = true}
itertools = {workspace = true}
git-version = {workspace = true}
rustsat-minisat = {workspace = true}
rustsat = {workspace = true}
paste = {workspace = true}
static_assertions = {workspace = true}
defile = {workspace = true}
ustr = {workspace = true}
polyquine = {workspace = true}
syn = {workspace = true}
quote = {workspace = true}
proc-macro2 = {workspace = true}

[dev-dependencies]
conjure-cp = {path = "../conjure-cp"}

[lints]
workspace = true

[package.metadata.cargo-shear]

ignored = [
  "conjure-cp" # used in doctests
  ]
