[package]
name = "minion_rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0.83", features = ["parallel"] }
bindgen = "0.68.1"
glob = "0.3.1"

