[package]
name = "minion_rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.57"

[build-dependencies]
bindgen = "0.69.4"
glob = "0.3.1"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic_in_result_fn = "warn"
panic = "warn"
todo = "warn"
