[package]
name = "conjure_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.90", features = ["full"] }
proc-macro2 = "1.0.89"
linkme = "0.3.31"

[lints]
workspace = true
