[package]
name = "conjure_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.79", features = ["full"] }
proc-macro2 = "1.0.87"
linkme = "0.3.27"

[lints]
workspace = true
