[package]
name = "conjure_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.58", features = ["full"] }
proc-macro2 = "1.0.80"
linkme = "0.3.25"

[lints]
workspace = true
