[package]
name = "conjure_essence_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
conjure_core = { path = "../conjure_core" }
tree-sitter-essence = { path = "../tree-sitter-essence" }
uniplate = "0.3.0"
tree-sitter = "0.24.7"
thiserror = "2.0.12"


[lints]
workspace = true
