[package]
name = "tests-integration"
version = "0.1.0"
edition = "2024"

[dependencies]
conjure-cp-rules = { path = "../crates/conjure-cp-rules" }

[lints]
workspace = true

[build-dependencies]
walkdir = "2.5.0"

[dev-dependencies]
conjure-cp = { path = "../crates/conjure-cp" }
conjure-cp-rules = { path = "../crates/conjure-cp-rules" }
conjure-cp-cli = { path = "../crates/conjure-cp-cli" }
git-version = "0.3.9"
glob = "0.3.3"
itertools = "0.14.0"
pretty_assertions = "1.4.1"
serde = "1.0.219"
toml = "0.9.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
tree-morph = { path = "../crates/tree-morph" }
uniplate = "0.4.3"
