name: Treesitter
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-treesitter.yml
      - crates/tree-sitter-essence/**
  pull_request:
    paths:
      - .github/workflows/ci-treesitter.yml
      - crates/tree-sitter-essence/**

env:
  # we define the following 3 values as the defaults here, matrix jobs may overwrite their values.
  # os: ubuntu-latest #Â commented out here as it is always defined in matrix jobs
  rust_release: stable
  compiler_profile: debug
  CARGO_INCREMENTAL: 0 # for smaller cache size

# see: https://github.com/tree-sitter/workflows
jobs:
  test:
    name: Test parser
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          path: repo

      - name: free_disk_space.sh
        run: repo/.github/workflows/tools/free_disk_space.sh

        # the tree-sitter actions expect this!
      - name: Make tree-sitter-essence the root directory
        run: cp -r repo/crates/tree-sitter-essence/* .

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2

      - name: Run parser and binding tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true

  fuzz:
    name: Fuzz scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          path: repo

      - name: Check for scanner changes
        id: scanner-check
        run: |-
          if git diff --quiet HEAD^ -- repo/crates/tree-sitter-essence/scanner.c; then
            printf 'changed=false\n' >> "$GITHUB_OUTPUT"
          else
            printf 'changed=true\n' >> "$GITHUB_OUTPUT"
          fi

        # the tree-sitter actions expect this!
      - name: Make tree-sitter-essence the root directory
        run: cp -r repo/crates/tree-sitter-essence/* .

      - name: Run the fuzzer
        uses: tree-sitter/fuzz-action@v4
        if: steps.scanner-check.outputs.changed == 'true'
