# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
# https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
name: 'solvers/kissat'

on:
  push:
    branches:
      - main # run for pushes to the main branch
    paths: 
      - solvers/kissat/**
      - Cargo.*
      - .github/workflows/kissat.yml
  pull_request:
    paths: 
      - solvers/kissat/**
      - Cargo.*
      - .github/workflows/kissat.yml
  workflow_dispatch:

jobs:
  ubuntu:
    name: 'Kissat: Ubuntu Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

          key: ${{ runner.os }}-stable-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-stable-

      - working-directory: ./solvers/kissat
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/kissat
        run: cargo build -vv

  mac:
    name: "Kissat: Mac Build"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

          key: ${{ runner.os }}-stable-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-stable-

      - working-directory: ./solvers/kissat
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/kissat 
        run: rustup target add aarch64-apple-darwin

      - working-directory: ./solvers/kissat
        run: cargo build -vv

  tests:
    name: "Kissat: Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

          key: ${{ runner.os }}-stable-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-stable-

      - working-directory: ./solvers/kissat
        run: rustup update stable && rustup default stable

      - working-directory: ./solvers/kissat
        run: cargo test
